import { BlogPost, Course } from './types';

export const COURSES: Course[] = [
  {
    id: 'c1',
    title: 'Excel Automation with Gemini',
    summary: 'Stop manually updating spreadsheets. Learn to use Gemini to write formulas and scripts.',
    description: 'Transform your daily spreadsheet grind into a streamlined workflow. This course focuses specifically on using Google Gemini to generate complex Excel formulas, VBA macros, and Google Apps Scripts without needing to be a coder.',
    level: 'Beginner',
    price: 450000,
    topics: ['Productivity', 'Excel', 'Gemini'],
    audience: ['Finance Analysts', 'Admin Staff', 'Accountants'],
    modules: ['Setting up Gemini for Data', 'Generating VLOOKUP & INDEX/MATCH', 'Automating Reports with Macros', 'Case Study: Monthly Expense Report'],
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80'
  },
  {
    id: 'c2',
    title: 'HR Workflow Optimization with ChatGPT',
    summary: 'Streamline recruitment, onboarding, and employee communications using ChatGPT.',
    description: 'Designed for HR professionals, this course teaches you how to build a library of reusable prompts for writing job descriptions, screening resumes, and drafting sensitive employee policy emails.',
    level: 'Intermediate',
    price: 550000,
    topics: ['HR', 'Communications', 'ChatGPT'],
    audience: ['HR Managers', 'Recruiters', 'People Ops'],
    modules: ['Prompt Engineering for HR', 'Automated Resume Screening', 'Drafting Contracts & Policies', 'Employee Engagement Surveys'],
    image: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80'
  },
  {
    id: 'c3',
    title: 'Meeting Minutes & Action Items with Claude',
    summary: 'Turn messy meeting transcripts into clean, actionable summaries in seconds.',
    description: 'Learn how to use Claude 3\'s large context window to process hour-long meeting transcripts, extracting key decisions, action items, and follow-up emails instantly.',
    level: 'Beginner',
    price: 300000,
    topics: ['Productivity', 'Management', 'Claude'],
    audience: ['Project Managers', 'Executive Assistants', 'Team Leads'],
    modules: ['Transcribing Audio', 'Structuring Summaries', 'Extracting Action Items', 'Integration with Notion/Asana'],
    image: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80'
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'b1',
    title: 'Generate Professional Email Replies Instantly',
    summary: 'A prompt to help you handle difficult client emails with a professional tone.',
    content: 'Act as a senior customer success manager. Draft a polite, professional, but firm email response to a client who is asking for a refund outside of the 30-day policy. Acknowledge their frustration, explain the policy clearly (referencing Section 4.2), and offer a 10% discount on their next renewal instead.',
    exampleOutput: 'Dear [Client Name],\n\nThank you for reaching out and sharing your concerns. I completely understand your frustration regarding the refund request.\n\nAfter reviewing your account, I must inform you that we are unable to process a refund at this time, as it falls outside our 30-day refund policy (referenced in Section 4.2 of our Terms of Service).',
    model: 'ChatGPT',
    category: 'Communication',
    date: 'Oct 12, 2023',
    relatedCourseId: 'c2',
    resultImage: 'https://images.unsplash.com/photo-1557200134-90327ee9fafa?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80'
  },
  {
    id: 'b2',
    title: 'Summarize Long PDF Reports',
    summary: 'Use Gemini 1.5 Pro to digest 50-page industry reports in 30 seconds.',
    content: 'I am uploading a PDF of the Q3 Market Analysis. Please extract the top 5 risks identified for the retail sector and summarize the 3 key growth opportunities recommended by the authors. Format this as a bulleted list for a slide deck.',
    exampleOutput: 'Risks:\n1. Supply chain volatility due to geopolitical tension.\n2. Rising energy costs impacting margins.\n3. Labor shortages in warehouse operations.\n\nOpportunities:\n1. AI adoption in customer service automation.\n2. Expansion into Tier 2 markets.',
    model: 'Gemini',
    category: 'Research',
    date: 'Oct 15, 2023',
    relatedCourseId: 'c1',
    resultImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80'
  },
  {
    id: 'b3',
    title: 'Claude for Coding Simple Python Scripts',
    summary: 'Automate file renaming in your "Downloads" folder using a script generated by Claude.',
    content: 'Write a Python script that organizes my "Downloads" folder. It should move all .jpg and .png files to a folder named "Images" and all .pdf files to a folder named "Documents". Add comments explaining how I can run this on Windows.',
    exampleOutput: 'import os\nimport shutil\n\n# Define directories\ndownloads_folder = "C:/Users/You/Downloads"\n\n# Loop through files\nfor filename in os.listdir(downloads_folder):\n    if filename.endswith(".jpg"): ...',
    model: 'Claude',
    category: 'Automation',
    date: 'Oct 20, 2023',
    relatedCourseId: 'c3',
    resultImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80'
  }
];